[package]
name = "gurobi"
version = "0.3.4"
authors = ["Yusuke Sasaki <y_sasaki@nuem.nagoya-u.ac.jp>", "Alice Ryhl <alice@ryhl.io>"]
description = "An unofficial Rust API for Gurobi optimizer"
categories = ["algorithms", "api-bindings", "mathematics", "science"]
keywords = ["optimization", "linear", "integer"]
license = "MIT"
repository = "https://github.com/ubnt-intrepid/rust-gurobi"
documentation = "https://docs.rs/gurobi/0.3.4/gurobi/"

[dependencies]
itertools = "0.10"

[dependencies.gurobi-sys]
path = "./gurobi-sys"
version = "0.3.0"
